# Generated by Django 5.1.5 on 2025-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('roles', models.TextField(help_text='Enter roles separated by commas')),
                ('quote', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='salt/images/')),
                ('order', models.IntegerField(default=0, help_text='Order in which to display the member')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'username'],
            },
        ),
    ]
