# Generated by Django 5.1.5 on 2025-03-31 19:27

from django.db import migrations

def add_member_data(apps, schema_editor):
    Member = apps.get_model('salt', 'Member')
    members_data = [
        {
            'username': 'puresalt',
            'full_name': 'james peck',
            'roles': ['team owner', 'player'],
            'quote': 'disturbingly good w/ dk',
            'image': 'salt/images/AP1GczPTQmYZbbY06fXtzloEN4faYHKKTrvL4bjkcHsX7Q54ir7zACv-wESWw1168-h1556-s-no-gm.png',
            'order': 1,
            'is_active': True
        },
        {
            'username': 'lui$',
            'full_name': 'luis oceguera',
            'roles': ['player'],
            'quote': 'norcal\'s goat',
            'image': 'salt/images/image0.jpg',
            'order': 2,
            'is_active': True
        },
        {
            'username': 'lonelymatt',
            'full_name': 'matt(hew) chung',
            'roles': ['video editor', 'webpage manager', 'player'],
            'quote': 'norcal\'s resident abb',
            'image': 'salt/images/IMG_7156.jpg',
            'order': 3,
            'is_active': True
        },
        {
            'username': 'nessboy12',
            'full_name': 'andrew nguyen',
            'roles': ['webpage manager', 'player'],
            'quote': 'adderall ness',
            'image': 'salt/images/IMG_7487.jpg',
            'order': 4,
            'is_active': True
        },
        {
            'username': 'shrutik',
            'full_name': 'shrutik kulkarni',
            'roles': ['team manager', 'player'],
            'quote': 'group leader',
            'image': 'salt/images/AP1GczPTQmYZbbY06fXtzloEN4faYHKKTrvL4bjkcHsX7Q54ir7zACv-wESWw1168-h1556-s-no-gm.png',
            'order': 5,
            'is_active': True
        },
        {
            'username': 'snorlax',
            'full_name': 'jason chou',
            'roles': ['commentator'],
            'quote': 'guildhouse employee',
            'image': 'salt/images/KS3K631k.jpg',
            'order': 6,
            'is_active': True
        },
        {
            'username': 'steamy',
            'full_name': 'eli levinson',
            'roles': ['player'],
            'quote': 'forever faded',
            'image': 'salt/images/9aa06cfd-d136-4d9a-b9ab-4a266f99988a.png',
            'order': 7,
            'is_active': True
        },
        {
            'username': 'marsbars',
            'full_name': 'Mario Valenzuela',
            'roles': ['commentator', 'player'],
            'quote': 'Mario Barrio',
            'image': 'salt/images/marsbars.png',
            'order': 8,
            'is_active': True
        },
        {
            'username': 'latios',
            'full_name': 'Michael Sheen',
            'roles': ['player'],
            'quote': '',
            'image': 'salt/images/latios.jpg',
            'order': 9,
            'is_active': True
        },
        {
            'username': 'fletchling',
            'full_name': 'melissa grove',
            'roles': ['player'],
            'quote': 'queen of north bay',
            'image': 'salt/images/Fletchling2.png',
            'order': 10,
            'is_active': True
        }
    ]
    
    for member_data in members_data:
        Member.objects.create(**member_data)

def remove_member_data(apps, schema_editor):
    Member = apps.get_model('salt', 'Member')
    Member.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_member_data, remove_member_data),
    ]
