# Generated by Django 5.1.5 on 2025-03-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0003_alter_member_full_name_alter_member_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
