# Generated by Django 5.1.5 on 2025-03-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0004_alter_member_roles'),
        ('salt', '0005_alter_member_roles'),
    ]

    operations = [
    ]
